name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: List directory contents
      run: ls -la
      
    - name: Find csproj files
      run: find . -name "*.csproj"
      
    - name: Restore dependencies
    run: dotnet restore
    # Resstaura as dependências do NuGET para as conexões com a Azure

    - name: Build with dotnet
      run: |
        # Especifica o caminho completo para o arquivo .csproj
        dotnet build ./CompetitionApp.csproj --configuration Release
      
    - name: dotnet publish
      run: |
        # Especifica o caminho completo para o arquivo .csproj
        dotnet publish ./CompetitionApp.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: '1911idsc'  # Será substituído pelo nome real do seu Web App
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{env.DOTNET_ROOT}}/myapp
